/** Demo product catalog — skeleton only, not real stock from any shop */
const PRODUCTS = [
  {
    id: 1,
    name: "Тепловізор HikMicro LYNX LE10 3.0",
    brand: "HikMicro",
    price: 22000,
    oldPrice: 28000,
    rating: 4.8,
    reviews: 15,
    res: "256",
    type: "mono",
    hit: true,
    popular: true,
    sale: 21,
  },
  {
    id: 2,
    name: "Тепловізор HikMicro LYNX LE15 3.0",
    brand: "HikMicro",
    price: 30000,
    oldPrice: 35000,
    rating: 4.7,
    reviews: 14,
    res: "384",
    type: "mono",
    hit: true,
    popular: true,
    sale: 14,
  },
  {
    id: 3,
    name: "Тепловізор HikMicro LYNX LH19 3.0",
    brand: "HikMicro",
    price: 44000,
    oldPrice: 51000,
    rating: 4.9,
    reviews: 17,
    res: "384",
    type: "mono",
    hit: true,
    popular: true,
    sale: 14,
  },
  {
    id: 4,
    name: "Тепловізор Rix Pocket K2",
    brand: "Rix",
    price: 24000,
    oldPrice: 27000,
    rating: 4.9,
    reviews: 20,
    res: "256",
    type: "mono",
    hit: false,
    popular: true,
    sale: 11,
  },
  {
    id: 5,
    name: "Тепловізор Rix Titan T6",
    brand: "Rix",
    price: 78000,
    oldPrice: 87000,
    rating: 4.6,
    reviews: 14,
    res: "640",
    type: "mono",
    hit: false,
    popular: true,
    sale: 10,
  },
  {
    id: 6,
    name: "Тепловізор ATN OTS-XLT 160 2.5-10X",
    brand: "ATN",
    price: 26700,
    oldPrice: 35435,
    rating: 4.5,
    reviews: 16,
    res: "256",
    type: "mono",
    hit: true,
    popular: true,
    sale: 25,
  },
  {
    id: 7,
    name: "Тепловізор HikMicro LYNX LH35 3.0",
    brand: "HikMicro",
    price: 58000,
    oldPrice: 63000,
    rating: 4.7,
    reviews: 10,
    res: "384",
    type: "mono",
    hit: false,
    popular: true,
    sale: 8,
  },
  {
    id: 8,
    name: "Тепловізор HikMicro LYNX LC06S",
    brand: "HikMicro",
    price: 14300,
    oldPrice: 22000,
    rating: 4.4,
    reviews: 15,
    res: "256",
    type: "mono",
    hit: true,
    popular: true,
    sale: 35,
  },
  {
    id: 9,
    name: "Тепловізор Nocpix (IRay) Vista H50R",
    brand: "INFIRAY",
    price: 137000,
    oldPrice: 145000,
    rating: 4.9,
    reviews: 17,
    res: "640",
    type: "mono",
    hit: false,
    popular: true,
    sale: 6,
  },
  {
    id: 10,
    name: "Тепловізор Pard Leopard 640-50 LRF",
    brand: "PARD",
    price: 83000,
    oldPrice: 120000,
    rating: 4.3,
    reviews: 3,
    res: "640",
    type: "mono",
    hit: true,
    popular: true,
    sale: 31,
  },
  {
    id: 11,
    name: "Тепловізор Rix Pocket K3",
    brand: "Rix",
    price: 33000,
    oldPrice: 39000,
    rating: 4.8,
    reviews: 21,
    res: "384",
    type: "mono",
    hit: true,
    popular: true,
    sale: 15,
  },
  {
    id: 12,
    name: "Тепловізор Rix Titan T3",
    brand: "Rix",
    price: 50000,
    oldPrice: 62000,
    rating: 4.7,
    reviews: 15,
    res: "384",
    type: "mono",
    hit: false,
    popular: true,
    sale: 19,
  },
  {
    id: 13,
    name: "Тепловізор HikMicro CONDOR LRF CQ50L 2.0",
    brand: "HikMicro",
    price: 112000,
    oldPrice: 135000,
    rating: 4.8,
    reviews: 14,
    res: "640",
    type: "mono",
    hit: true,
    popular: true,
    sale: 17,
  },
  {
    id: 14,
    name: "Тепловізор HikMicro FALCON FQ50L 2.0",
    brand: "HikMicro",
    price: 112000,
    oldPrice: 117000,
    rating: 4.6,
    reviews: 6,
    res: "640",
    type: "mono",
    hit: true,
    popular: true,
    sale: 4,
  },
  {
    id: 15,
    name: "Тепловізор HikMicro LYNX LH25 3.0",
    brand: "HikMicro",
    price: 52000,
    oldPrice: 57000,
    rating: 4.8,
    reviews: 18,
    res: "384",
    type: "mono",
    hit: true,
    popular: true,
    sale: 9,
  },
  {
    id: 16,
    name: "Тепловізор Pulsar Axion XG30",
    brand: "PULSAR",
    price: 89000,
    oldPrice: 99000,
    rating: 4.9,
    reviews: 12,
    res: "640",
    type: "mono",
    hit: true,
    popular: false,
    sale: 10,
  },
];

const BRANDS = [
  "HikMicro",
  "Rix",
  "PULSAR",
  "PARD",
  "INFIRAY",
  "ATN",
  "AGM",
  "FLIR",
  "ThermEye",
  "Guide",
  "NVECTECH",
  "Sytong",
];

const REVIEWS = [
  {
    product: "Тепловізор HikMicro FALCON FQ25",
    text: "Отримавши свій тепловізор, відчуваю величезну вдячність за професійний підбір та швидку доставку...",
    author: "Андрій",
    date: "17/02/2024",
  },
  {
    product: "Тепловізор Hikmicro Budgie BC06",
    text: "Купував цей прилад рік тому. Працює без проблем. Купив ще один на подарунок...",
    author: "Василь",
    date: "23/09/2023",
  },
  {
    product: "Тепловізор Pulsar Helion XP38",
    text: "Відмінний прилад. Рекомендую всім, хто шукає надійний тепловізор для поля.",
    author: "Юрій",
    date: "07/03/2020",
  },
  {
    product: "Тепловізор ThermEye Cyclops 650",
    text: "Добре фіксує теплові об'єкти в русі, показує чітку картинку без змазаних деталей...",
    author: "Давид",
    date: "11/06/2022",
  },
  {
    product: "Тепловізор Rix Pocket K2",
    text: "Надійний і простий. Рекомендую для старту.",
    author: "Іван",
    date: "08/04/2025",
  },
  {
    product: "Тепловізор HikMicro GRYPHON GH35",
    text: "Швидка доставка. Самим тепловізором задоволений, повністю відповідає характеристикам.",
    author: "Сергій",
    date: "10/08/2022",
  },
];
